services:
  krypto-dashboard-web:
    image: ghcr.io/kuranez/krypto-dashboard-web:latest
    user: "10000:1003"  # webadmin:psacln
    ports:
      - "5013:5013"
    env_file:
      - keys.env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

