version: '3.8'

services:
  krypto-dashboard-web:
    build: .
    image: ghcr.io/kuranez/krypto-dashboard-web:latest
    user: "10000:1003"  # webadmin:psacln
    ports:
      - "5013:5013"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - BINANCE_API_KEY=${BINANCE_API_KEY:-}

